name: qModSuite
author: RetroHQ Development
version: 1.0 SNAPSHOT
main: us.retrohq.qmodsuite.Main

commands:
  invsee:
    aliases: []
  rename:
    description: Rename the item you are holding in your hand
    usage: /<command>