name: qModSuite
author: RetroHQ Development
version: 1.0 SNAPSHOT
main: us.retrohq.qmodsuite.Main

commands:
  gm:
    aliases: []
  gmc:
    aliases: []
  gms:
    aliases: []
  tp:
    aliases: [teleport]
  tphere:
    aliases: [teleporthere]
  invsee:
    aliases: inventorysee]
  clearchat:
    aliases: [cc]
  clear:
    aliases: []
  mod:
    aliases: []